# Ryven Kitty defaults
font_family JetBrains Mono
font_size 11
include /usr/share/kitty-themes/themes/Catppuccin-Mocha.conf
cursor_shape block
cursor_blink_interval 0
window_padding_width 8
background_opacity 0.95
map ctrl+shift+c copy_to_clipboard
map ctrl+shift+v paste_from_clipboard
shell_integration no-cursor
