# Ryven Plasma Login Manager defaults: dark Catppuccin Mocha + Ryven wallpaper
[Theme]
Theme=org.kde.breezedark
ColorScheme=CatppuccinMochaMauve
Font=Inter,10,-1,5,50,0,0,0,0,0,Regular
CursorTheme=Bibata-Modern-Ice,CursorSize=24
Wallpaper=/usr/share/wallpapers/ryven-default/contents/images/dark.svg

[General]
Numlock=on
EnableHiDPIScaling=true
WaylandEnable=true
