general {
    gaps_in = 4
    gaps_out = 8
    border_size = 2
    col.active_border = 0x89b4faee
    col.inactive_border = 0x45475a99
    layout = dwindle
    allow_tearing = false   # default off; per-window window rules override
    resize_on_border = true
    extend_border_grab_area = 8
    no_cursor_warps = true
    mouse_move_enables_dpms = false
    follow_mouse = 1
    always_follow_on_dnd = true
    focus_on_activate = true
}

decoration {
    rounding = 8
    blur { enabled = false; size = 3; passes = 1; new_optimizations = true }
    drop_shadow = true
    shadow_range = 4
    shadow_render_power = 3
    col.shadow = 0x1e1e2eee
    shadow_offset = 1 1
    active_opacity = 1.0
    inactive_opacity = 1.0
    dim_inactive = false
    dim_strength = 0.1
    screen_shader = /usr/share/hypr/shaders/blue-light-filter.glsl  # default off
}
