input {
    kb_layout = us
    kb_variant =
    kb_options =
    kb_model =

    follow_mouse = 1
    mouse_refocus = false

    float_switch_override_focus = 1

    sensitivity = 0     # 1:1 raw
    accel_profile = flat # no pointer acceleration (gaming default)
    natural_scroll = false

    left_handed = false
    middle_button_emulation = false

    scroll_method = 2fg
    scroll_button = 273
    scroll_button_lock = false
    scroll_factor = 1.0

    touchpad {
        natural_scroll = true
        tap_button_map = lrm
        tap_to_click = true
        drag_lock = false
        middle_button_emulation = false
        tap_and_drag = true
        accel_profile = adaptive
        pointer_accel = 0.3
    }
}

device {
    name = *
    repeat_rate = 50
    repeat_delay = 300
    left_handed = false
    natural_scroll = false
    scroll_factor = 1.0
}

# Libinput 1:1 flat for all mice
device:mouse {
    accel_profile = flat
    sensitivity = 0
}
