# Ryven Navy (coolors 0d1b2a-1b263b-415a77-778da9-e0e1dd)
background {
    monitor =
    path = /usr/share/wallpapers/Ryven/contents/images/3840x2160.png
    blur_passes = 2
    color = 0d1b2acc
}

input-field {
    monitor =
    size = 400, 60
    placeholder_text = <i>password</i>
}

label {
    monitor =
    text = $TIME
    font_size = 64
    font_family = Inter
    position = 0, 80
    halign = center
    valign = center
}

color {
    text-color = e0e1dd
    text-error-color = d98a8a
    input-bg-color = 1b263bcc
    input-border-color = 415a77
    input-fg-color = e0e1dd
    input-fg-active-color = 778da9
    ring-color = 778da9
}
