background {
    monitor =
    path = /usr/share/wallpapers/Ryven/contents/images/3840x2160.png
    blur_passes = 2
}

input-field {
    monitor =
    size = 400, 60
    placeholder_text = <i>password</i>
}

label {
    monitor =
    text = $TIME
    font_size = 64
    font_family = Inter
    position = 0, 80
    halign = center
    valign = center
}
